### ISSUE TITLE
found few bugs 

### ISSUE THREAD

**Issue by TheDarkNoise** [TheUnknownGentlemen/RocketBot#1]
1. Auto-walk gives me a wierd message 
   https://gyazo.com/41c50c1843537a5de056ff0e82e6d79c
2. when u walk towards on point and then u select a new point u wanna walk to instead 
   right click on the map where u want to walk and then mean time the trainer walks u make a other click on a diffrent spot and the trainer act's wierd :P

https://gyazo.com/41762b1255b11aa9f4b94e6090fd435e
https://gyazo.com/c390c4ca858836a21c46d96d051caec6
1. notice  also that pokestops , Pokemon stops working
   mean pokestops that first generate works fine and the map wont spawn more pokestops
   https://gyazo.com/6ec2ab4e05d6197cf49cc9395ea93e40 - edited
   https://gyazo.com/ac4468bd8fc935c817cbe2ebca531a7a
   pokemon wont spawn/popup after a while

3.1. wanna add that hatch eggs stop working same time as the pokestops and pokemon

3.2. standing next to a pokestop and its say outofrange
https://gyazo.com/50ce8bcf4d29e46beaba028169bec5e4
1. i think its would be great IF the catch could miss as well 
2. i think it would be great to know how many pokemon u have catched and how many pokestops u have visit 

reason is the new ban system is catch 1k - 2k pokemon and pokestops
if u catch more or visit pokestops more then 1k-2k a day u got bigger chance u get banned
1. if u click on a pokestop BEFORE u get to it u cant use farm on it
2. logging in u need to press it twice before u get logined in and start use it - added

**Comment by wertzui** [comment]
1. should be fixed with 4157fe52516b39713163807daa8d3fb07d8d01fb
2. should be fixed with 6faea135feb9919ee5c8a4b9708e84b39c94b0c1
3. looks like you have problems sending your updated position to the server, maybe you got softbanned because of 2.?

**Comment by TheDarkNoise** [comment]
(3. im not been soft banned  always double checking just did now and i can still use pokestop's , catch pokemon

do u think u can add a marker or something on the map where u selected your trainer to walk towards ?

**Comment by TheDarkNoise** [comment]
notice also that Recycle is not working 100%  first it works  and then its not working and i need to relog to fix it for a while :P

**Comment by wertzui** [comment]
3.2 is fixed with 2ff014381394cd32e4592dafb426d970b7462335

I will close this Isse as all issues that we can fix should be fixed now.
Please open separate Issues for separate bugs/ideas, so it is easier to keep track.
